export const leftNavLinks = [
  {
    label: "Create Showject",
    link: "/create-showject",
  },
  {
    label: "Create Showject",
    link: "/create-showject",
  },
];

export const smallProjects = [
  {
    title: "Easybank Landing Page",
    imgSrc: `/images/Small Projects/sm15.png`,
    techUsed: ["Astro", "React", "Tailwind CSS"],
    githubLink: `https://github.com/ckeanudev/frontendmentor-easybank`,
    liveLink: `https://frontendmentor-easybank-six.vercel.app/`,
    loved: 408,
  },
  {
    title: "Ecommerce Product",
    imgSrc: `/images/Small Projects/sm14.png`,
    techUsed: ["React"],
    githubLink: `https://github.com/ckeanudev/frontend-mentor-ecommerce-product`,
    liveLink: `https://frontend-mentor-ecommerce-product.vercel.app`,
    loved: 398,
  },
  {
    title: "Results Summary Component",
    imgSrc: `/images/Small Projects/sm13.png`,
    techUsed: ["HTML", "CSS"],
    githubLink: `https://github.com/ckeanudev/frontend-mentor-results-summary-component`,
    liveLink: `https://frontend-mentor-results-summary-component-two.vercel.app`,
    loved: 379,
  },
  {
    title: "Rock, Paper, Scissors Game",
    imgSrc: `/images/Small Projects/sm12.png`,
    techUsed: ["React"],
    githubLink: `https://github.com/ckeanudev/frontend-mentor-rock-paper-scissors-game`,
    liveLink: `https://ckeanu-frontend-mentor-game.netlify.app`,
    loved: 265,
  },
  {
    title: "REST Countries API",
    imgSrc: `/images/Small Projects/sm11.png`,
    techUsed: ["React", "API"],
    githubLink: `https://github.com/ckeanudev/dev-rest-country-api`,
    liveLink: `https://ckeanu-country-api.netlify.app`,
    loved: 142,
  },
  {
    title: "Job Listings w/ Filtering",
    imgSrc: `/images/Small Projects/sm10.png`,
    techUsed: ["React"],
    githubLink: `https://github.com/ckeanudev/frontend-mentor-job-listing`,
    liveLink: `https://ckeanu-job-listing.netlify.app`,
    loved: 123,
  },
  {
    title: "Free Games Site",
    imgSrc: `/images/Small Projects/sm9.png`,
    techUsed: ["React", "API"],
    githubLink: `https://github.com/ckeanudev/dev-free-games-list`,
    liveLink: `https://ckeanu-free-games.netlify.app`,
  },
  {
    title: "Small Meal App",
    imgSrc: `/images/Small Projects/sm8.png`,
    techUsed: ["React", "API"],
    githubLink: `https://github.com/ckeanudev/dev-react-meal-app`,
    liveLink: `https://ckeanu-meal-app.netlify.app`,
  },
  {
    title: "COVID-19 Case Tracker App",
    imgSrc: `/images/Small Projects/sm7.png`,
    techUsed: ["React", "API"],
    githubLink: `https://github.com/ckeanudev/dev-covid-19-tracker-system`,
    liveLink: `https://ckeanu-covid-19-tracker-system.netlify.app`,
  },
  {
    title: "Cryptocurrency Price Tracker App",
    imgSrc: `/images/Small Projects/sm6.png`,
    techUsed: ["React", "API"],
    githubLink: `https://github.com/ckeanudev/dev-crypto-price-tracker`,
    liveLink: `https://ckeanu-crypto-price-tracker.netlify.app`,
  },
  {
    title: "To-Do List App",
    imgSrc: `/images/Small Projects/sm5.png`,
    techUsed: ["HTML", "CSS", "JS"],
    githubLink: `https://github.com/ckeanudev/vanilla-javascript-to-do-list`,
    liveLink: `https://to-do-list-ckeanu.netlify.app`,
  },
  {
    title: "Huddle Landing Page",
    imgSrc: `/images/Small Projects/sm4.png`,
    techUsed: ["HTML", "CSS"],
    githubLink: `https://github.com/ckeanudev/Huddle-landing-page`,
    liveLink: `https://huddle-landing-page-ckeanu.netlify.app`,
  },
  {
    title: "Project Tracking Intro Component",
    imgSrc: `/images/Small Projects/sm3.png`,
    techUsed: ["HTML", "CSS"],
    githubLink: `https://github.com/ckeanudev/Project-tracking-intro-component`,
    liveLink: `https://project-tracking-intro-component-ckeanu.netlify.app`,
  },

  {
    title: "NFT Preview Card Component",
    imgSrc: `/images/Small Projects/sm2.png`,
    techUsed: ["HTML", "CSS"],
    githubLink: `https://github.com/ckeanudev/NFT-preview-card-component`,
    liveLink: `https://nft-preview-card-component-ckeanu.netlify.app`,
  },
  {
    title: "Order Summary Card",
    imgSrc: `/images/Small Projects/sm1.png`,
    techUsed: ["HTML", "CSS"],
    githubLink: `https://github.com/ckeanudev/Order-summary-card`,
    liveLink: `https://order-summary-card-ckeanu.netlify.app`,
  },
];
